---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "collabora-code.fullname" . }}
data:
  DONT_GEN_SSL_CERT: "{{ .Values.collabora.DONT_GEN_SSL_CERT }}"
  dictionaries: {{ .Values.collabora.dictionaries }}
  {{- range $k,$v := .Values.collabora.aliasgroups }}
  {{- $alias := $v.domain }}
  {{- if $v.aliases }}
  {{- $alias := printf "%s,https://%s:443" $alias (join "|" $v.aliases ) }}
  aliasgroup{{ add $k 1 }}: {{ $alias }}
  {{- else }}
  aliasgroup{{ add $k 1 }}: {{ $alias }}
  {{- end }}
  {{- end }}
  {{- with .Values.collabora.domain }}
  aliasgroup{{ add (len $.Values.collabora.aliasgroups) 1 }}: {{ printf "https://%s:443" (. | replace "\\" "") }}
  {{- end }}
  extra_params: {{ .Values.collabora.extra_params }}
  server_name: {{ .Values.collabora.server_name }}
