apiVersion: v1
kind: Secret
metadata:
  name: {{ include "collabora-code.fullname" . }}
  labels:
    {{- include "collabora-code.labels" . | nindent 4 }}
data:
  username: {{ .Values.collabora.username | b64enc }}
  password: {{ .Values.collabora.password | b64enc }}